[build]
  command = "echo 'No build needed'"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "supabase/client.js"
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200